<script setup>
import { computed, onMounted, ref } from 'vue'
import { all, task } from '../../api'
import { inr } from '../../utils/currency'
import InfoTip from '../../components/InfoTip.vue'

const loading=ref(true), busy=ref(false), error=ref(''), message=ref('')
const data=ref({settings:{inventory_mode:'none',inventory_advanced:0},locations:[],stock:[],summary:{},movements:[],transfers:[]})
const products=ref([]), tab=ref('stock'), locationFilter=ref('')
const settings=ref({mode:'none',advanced:false})
const adjust=ref({product_id:'',location_id:'',kind:'purchase',quantity:'',unit_cost:'',batch_no:'',expiry_date:'',serial_numbers:'',note:''})
const place=ref({name:'',type:'shop',address:'',is_default:false,active:true})
const transfer=ref({from_location_id:'',to_location_id:'',transfer_date:new Date().toISOString().slice(0,10),notes:'',items:[{product_id:'',quantity:''}]})
const search=ref(''), stockFilter=ref('all')
const modeText={none:'Billing only',warn:'Show stock',strict:'Control stock'}
const kindText={opening:'Opening Stock',purchase:'Purchase Stock In',purchase_return:'Purchase Return to Supplier',adjustment:'Stock Correction',damage:'Damaged / Expired',count:'Physical Stock Count'}

const filteredStock=computed(()=>data.value.stock.filter(s=>{
  const q=search.value.toLowerCase(); if(q&&!`${s.name} ${s.sku||''} ${s.barcode||''}`.toLowerCase().includes(q))return false
  if(stockFilter.value==='low')return +s.quantity>0&&+s.quantity<=+s.reorder_level
  if(stockFilter.value==='out')return +s.quantity<=0
  if(stockFilter.value==='dead')return +s.quantity>0&&s.last_moved_at&&new Date(s.last_moved_at)<new Date(Date.now()-90*86400000)
  return true
}))
async function load(){loading.value=true;error.value='';try{const [o,p]=await Promise.all([task('Inventory','overview',locationFilter.value?{location_id:locationFilter.value}:{}),all('Product')]);data.value=o.data.data;products.value=(p.data.data||[]).filter(x=>x.type==='product');settings.value={mode:data.value.settings.inventory_mode,advanced:!!+data.value.settings.inventory_advanced};if(!adjust.value.location_id)adjust.value.location_id=data.value.defaultId;if(!transfer.value.from_location_id)transfer.value.from_location_id=data.value.defaultId}catch(e){error.value=e.response?.data?.message||'Could not load stock.'}loading.value=false}
async function run(method,payload,ok){busy.value=true;error.value='';message.value='';try{await task('Inventory',method,payload);message.value=ok;await load()}catch(e){error.value=e.response?.data?.message||'Could not save.'}busy.value=false}
const saveSettings=()=>run('saveSettings',{mode:settings.value.mode,advanced:settings.value.advanced},'Stock settings saved.')
const saveLocation=()=>run('saveLocation',place.value,'Shop / Godown saved.')
function saveAdjustment(){const payload={...adjust.value,serial_numbers:adjust.value.serial_numbers.split(/[,\n]/).map(x=>x.trim()).filter(Boolean)};run('adjust',payload,'Stock updated.');adjust.value={...adjust.value,product_id:'',quantity:'',unit_cost:'',batch_no:'',expiry_date:'',serial_numbers:'',note:''}}
function addTransferRow(){transfer.value.items.push({product_id:'',quantity:''})}
const saveTransfer=()=>run('createTransfer',transfer.value,'Transfer prepared. Send it when goods leave the shop.')
const dispatch=id=>run('dispatchTransfer',{id},'Stock sent and marked In transit.')
const receive=id=>run('receiveTransfer',{id},'Stock received at destination.')
onMounted(load)
</script>

<template>
<div class="mx-auto max-w-7xl space-y-5 p-4 pb-24 lg:p-7">
  <div class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-bold text-gray-900">Stock</h1><p class="text-sm text-gray-500">Your simple digital stock book for every shop and godown.</p></div><div class="rounded-full bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-700">{{ modeText[settings.mode] }}</div></div>
  <div v-if="error" class="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{{error}}</div><div v-if="message" class="rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-700">{{message}}</div>
  <div class="flex gap-2 overflow-x-auto pb-1"><button v-for="t in [['stock','Current Stock'],['in','Stock In / Correction'],['transfer','Move Stock'],['places','Shops / Godowns'],['history','Stock History'],['settings','Settings']]" :key="t[0]" @click="tab=t[0]" class="whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold" :class="tab===t[0]?'bg-blue-600 text-white':'bg-white border text-gray-600'">{{t[1]}}</button></div>
  <div v-if="loading" class="rounded-2xl bg-white p-12 text-center text-gray-500">Loading your stock book…</div>
  <template v-else>
    <section v-if="tab==='stock'" class="space-y-4">
      <div class="grid grid-cols-2 gap-3 lg:grid-cols-5"><div v-for="c in [[data.summary.products,'Stock Items','Products whose stock is maintained'],[data.summary.low,'Low Stock','Products at or below the alert quantity'],[data.summary.out,'Out of Stock','Products with no available stock'],[data.summary.dead,'Dead Stock','Stock with no movement for more than 90 days'],...(data.summary.value!=null?[[inr(data.summary.value||0),'Stock Value','Current quantity × average purchase cost']]:[])]" :key="c[1]" class="rounded-2xl border bg-white p-4"><div class="flex items-center gap-2 text-xs font-semibold uppercase text-gray-500">{{c[1]}} <InfoTip :text="c[2]"/></div><p class="mt-2 text-2xl font-bold">{{c[0]}}</p></div></div>
      <div class="flex flex-wrap gap-2"><input v-model="search" class="min-w-52 flex-1 rounded-xl border px-3 py-2 text-sm" placeholder="Search product, SKU or barcode"/><select v-model="locationFilter" @change="load" class="rounded-xl border px-3 py-2 text-sm"><option value="">All Shops / Godowns</option><option v-for="l in data.locations.filter(x=>+x.active)" :value="l.id" :key="l.id">{{l.name}}</option></select><select v-model="stockFilter" class="rounded-xl border px-3 py-2 text-sm"><option value="all">All products</option><option value="low">Low stock</option><option value="out">Out of stock</option><option value="dead">Dead stock (90+ days)</option></select></div>
      <div class="overflow-hidden rounded-2xl border bg-white"><div v-if="!filteredStock.length" class="p-10 text-center text-sm text-gray-500">No stock items yet. Enable “Maintain stock” on a product, then add opening stock.</div><div v-for="s in filteredStock" :key="`${s.product_id}-${s.location_id}`" class="flex items-center gap-3 border-b p-4 last:border-0"><div class="min-w-0 flex-1"><p class="font-semibold text-gray-900">{{s.name}}</p><p class="text-xs text-gray-500">{{s.location_name}}<span v-if="s.sku"> · SKU {{s.sku}}</span></p></div><span v-if="+s.quantity<=0" class="rounded-full bg-red-50 px-2 py-1 text-xs font-bold text-red-700">OUT</span><span v-else-if="+s.quantity<=+s.reorder_level" class="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">LOW</span><div class="text-right"><p class="text-lg font-bold">{{+s.quantity}} {{s.unit}}</p><p v-if="s.average_cost != null" class="text-xs text-gray-500">{{inr(+s.quantity*+s.average_cost)}}</p></div></div></div>
    </section>
    <section v-if="tab==='in'" class="mx-auto max-w-2xl rounded-2xl border bg-white p-5 space-y-4"><div class="flex items-center gap-2"><h2 class="text-lg font-bold">Stock In / Correction</h2><InfoTip text="Use Purchase Stock In when goods arrive. Use Stock Correction only to fix a counting mistake. Every change stays in Stock History."/></div><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Reason<select v-model="adjust.kind" class="mt-1 w-full rounded-xl border p-2.5"><option v-for="(v,k) in kindText" :value="k" :key="k">{{v}}</option></select></label><label class="text-sm font-medium">Shop / Godown<select v-model="adjust.location_id" class="mt-1 w-full rounded-xl border p-2.5"><option v-for="l in data.locations.filter(x=>+x.active)" :value="l.id" :key="l.id">{{l.name}}</option></select></label><label class="text-sm font-medium sm:col-span-2">Product<select v-model="adjust.product_id" class="mt-1 w-full rounded-xl border p-2.5"><option value="">Choose product</option><option v-for="p in products.filter(x=>+x.track_stock)" :value="p.id" :key="p.id">{{p.name}} ({{p.unit}})</option></select></label><label class="text-sm font-medium">Quantity <InfoTip text="For correction, enter + to add or - to reduce. Damaged / Expired always reduces stock."/><input v-model="adjust.quantity" type="number" step="0.001" class="mt-1 w-full rounded-xl border p-2.5"/></label><label class="text-sm font-medium">Purchase cost per unit (₹)<input v-model="adjust.unit_cost" type="number" step="0.01" class="mt-1 w-full rounded-xl border p-2.5"/></label><template v-if="settings.advanced"><label class="text-sm font-medium">Batch / Lot number<input v-model="adjust.batch_no" class="mt-1 w-full rounded-xl border p-2.5"/></label><label class="text-sm font-medium">Expiry date<input v-model="adjust.expiry_date" type="date" class="mt-1 w-full rounded-xl border p-2.5"/></label><label class="text-sm font-medium sm:col-span-2">Serial / IMEI numbers <InfoTip text="Enter one number per line or separate with commas. Useful for mobiles and electronics."/><textarea v-model="adjust.serial_numbers" rows="2" class="mt-1 w-full rounded-xl border p-2.5"/></label></template><label class="text-sm font-medium sm:col-span-2">Reason / note<input v-model="adjust.note" class="mt-1 w-full rounded-xl border p-2.5" placeholder="Example: Supplier bill 174, physical count correction"/></label></div><button @click="saveAdjustment" :disabled="busy||!adjust.product_id||!adjust.quantity" class="rounded-xl bg-blue-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">Update Stock</button></section>
    <section v-if="tab==='transfer'" class="grid gap-5 lg:grid-cols-2"><div class="rounded-2xl border bg-white p-5 space-y-4"><div class="flex gap-2"><h2 class="text-lg font-bold">Move Stock</h2><InfoTip text="Stock leaves the first location when you tap Send. It reaches the second location only when the receiving person confirms Received."/></div><div class="grid grid-cols-2 gap-3"><select v-model="transfer.from_location_id" class="rounded-xl border p-2.5"><option value="">From Shop / Godown</option><option v-for="l in data.locations" :value="l.id" :key="l.id">{{l.name}}</option></select><select v-model="transfer.to_location_id" class="rounded-xl border p-2.5"><option value="">To Shop / Godown</option><option v-for="l in data.locations" :value="l.id" :key="l.id">{{l.name}}</option></select></div><div v-for="(i,n) in transfer.items" :key="n" class="flex gap-2"><select v-model="i.product_id" class="min-w-0 flex-1 rounded-xl border p-2.5"><option value="">Product</option><option v-for="p in products.filter(x=>+x.track_stock)" :value="p.id" :key="p.id">{{p.name}}</option></select><input v-model="i.quantity" type="number" step="0.001" placeholder="Qty" class="w-24 rounded-xl border p-2.5"/></div><button @click="addTransferRow" class="text-sm font-semibold text-blue-600">+ Add another product</button><textarea v-model="transfer.notes" class="w-full rounded-xl border p-2.5" placeholder="Optional note"/><button @click="saveTransfer" :disabled="busy" class="rounded-xl bg-blue-600 px-5 py-2.5 font-semibold text-white">Prepare Transfer</button></div><div class="rounded-2xl border bg-white"><div class="border-b p-4 font-bold">Recent Transfers</div><div v-for="t in data.transfers" :key="t.id" class="border-b p-4"><div class="flex justify-between gap-2"><div><p class="font-semibold">{{t.transfer_no}}</p><p class="text-xs text-gray-500">{{t.from_name}} → {{t.to_name}}</p></div><span class="text-xs font-bold uppercase">{{t.status}}</span></div><div class="mt-3 flex gap-2"><button v-if="t.status==='draft'" @click="dispatch(t.id)" class="rounded-lg bg-amber-500 px-3 py-1.5 text-xs font-bold text-white">Send Stock</button><button v-if="t.status==='dispatched'" @click="receive(t.id)" class="rounded-lg bg-green-600 px-3 py-1.5 text-xs font-bold text-white">Confirm Received</button></div></div></div></section>
    <section v-if="tab==='places'" class="grid gap-5 lg:grid-cols-2"><div class="rounded-2xl border bg-white p-5 space-y-4"><div class="flex gap-2"><h2 class="text-lg font-bold">Add Shop / Godown</h2><InfoTip text="Single-shop users need only Main Shop. Add a godown or branch only when stock is physically stored there."/></div><input v-model="place.name" class="w-full rounded-xl border p-2.5" placeholder="Example: Main Shop, Central Godown"/><select v-model="place.type" class="w-full rounded-xl border p-2.5"><option value="shop">Shop / Branch</option><option value="godown">Godown</option><option value="damaged">Damaged / Returns Store</option></select><textarea v-model="place.address" class="w-full rounded-xl border p-2.5" placeholder="Address (optional)"/><label class="flex gap-2 text-sm"><input v-model="place.is_default" type="checkbox"/> Use as default billing location</label><button @click="saveLocation" class="rounded-xl bg-blue-600 px-5 py-2.5 font-semibold text-white">Save Location</button></div><div class="rounded-2xl border bg-white"><div v-for="l in data.locations" :key="l.id" class="flex items-center justify-between border-b p-4"><div><p class="font-semibold">{{l.name}}</p><p class="text-xs capitalize text-gray-500">{{l.type}} <span v-if="+l.is_default">· Default</span></p></div><span :class="+l.active?'text-green-700':'text-gray-400'" class="text-xs font-bold">{{+l.active?'ACTIVE':'INACTIVE'}}</span></div></div></section>
    <section v-if="tab==='history'" class="overflow-hidden rounded-2xl border bg-white"><div class="border-b p-4"><h2 class="font-bold">Stock History</h2><p class="text-xs text-gray-500">Permanent audit trail. Posted entries are reversed, never silently deleted.</p></div><div v-for="m in data.movements" :key="m.id" class="flex gap-3 border-b p-4"><div class="flex-1"><p class="font-semibold">{{m.product_name}}</p><p class="text-xs text-gray-500">{{m.location_name}} · {{m.movement_type.replaceAll('_',' ')}} · {{m.note||'No note'}}</p><p class="text-[11px] text-gray-400">{{m.occurred_at}} · {{m.user_name||'System'}}</p></div><div class="text-right"><p class="font-bold" :class="+m.quantity>=0?'text-green-700':'text-red-700'">{{+m.quantity>=0?'+':''}}{{+m.quantity}} {{m.unit}}</p><p class="text-xs text-gray-500">Balance {{+m.balance_after}}</p></div></div></section>
    <section v-if="tab==='settings'" class="mx-auto max-w-3xl rounded-2xl border bg-white p-5 space-y-5"><div><h2 class="text-lg font-bold">How should stock work?</h2><p class="text-sm text-gray-500">Choose what matches this business. You can change it later.</p></div><label v-for="m in [{id:'none',name:'Billing only',desc:'Do not reduce or check stock. Best for services or shops maintaining stock elsewhere.'},{id:'warn',name:'Show stock',desc:'Maintain stock and warn the cashier, but allow a sale when stock is short.'},{id:'strict',name:'Control stock',desc:'Maintain stock and stop billing above the available quantity.'}]" :key="m.id" class="flex cursor-pointer gap-3 rounded-xl border p-4" :class="settings.mode===m.id?'border-blue-500 bg-blue-50':''"><input v-model="settings.mode" type="radio" :value="m.id"/><div><div class="flex gap-2 font-bold">{{m.name}} <InfoTip :text="m.desc"/></div><p class="text-sm text-gray-600">{{m.desc}}</p></div></label><label class="flex gap-3 rounded-xl border p-4"><input v-model="settings.advanced" type="checkbox"/><div><p class="font-bold">Show advanced trade fields</p><p class="text-sm text-gray-500">Batch, expiry and serial / IMEI fields for medical, food and electronics shops.</p></div></label><button @click="saveSettings" class="rounded-xl bg-blue-600 px-5 py-2.5 font-semibold text-white">Save Settings</button></section>
  </template>
</div>
</template>
